name: WEB-CI/CD

on:  
  pull_request:
    branches: ["Dev-MurderMystery-Web"]  

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node & Lint Tools
      run: |
        npm install -g htmlhint stylelint stylelint-config-standard

    - name: Run HTMLHint
      run: htmlhint index.html

    - name: Run Stylelint
      run: stylelint "style.css"

    - name: Install Puppeteer
      run: |
        npm init -y
        npm install puppeteer
    
    - name: Install Puppeteer Chrome
      run: npx puppeteer browsers install chrome

    - name: Run Integration Tests
      run: node smoke-test.js
    

